### ISSUE TITLE
Disable redirect for homepage

### ISSUE THREAD

**Issue by tufanayd** [Vinai/loginonlycatalog#17]
How can I disable redirect for homepage?

At the moment I am listing some products in my homepage and your extension is redirecting the user to login page, is there a way of bypassing this for homepage only?

If yes, how?

Thanks

**Comment by Vinai** [comment]
Add the string `cms/index/index` into the field "Disable on routes" in the modules system configuration settings.

**Comment by tufanayd** [comment]
It worked, thanks a lot.
