### ISSUE TITLE
Disable on routes (pages)

### ISSUE THREAD

**Issue by pauldonnelly** [Vinai/loginonlycatalog#18]
I cannot seem to disable a route to a specific page. Is it possible with this module?

**Comment by Vinai** [comment]
It is only possible to disable the module based on a route consisting of frontName (e.g customer), frontName + controller (e.g. checkout/cart), or frontName, controller and action (e.g. `cms/index/index`).

**Comment by pauldonnelly** [comment]
Ah ok. Thanks Vinai :)
